name: HemlockforSocrates
favicon: null
layout_spectrum: 0.5286955840419978
typography_spectrum: 0.4384060010779649
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5022902612108737
  lightness: 0.3880150313489139
  saturation: 0.7869873542804271
  rhythmicContrast: 0.48784929513931274
purpose: []
