typography_spectrum: 0.4384060010779649
color:
  brandColors:
    - '#fbf8f3'
    - '#e5c0a4'
    - '#c18458'
    - '#010104'
    - '#434434'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.7869873542804271
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.83301
analytics:
  google: null
  facebook: null
  twitter: null
name: HemlockforSocrates
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Freelance Writer for hire
description: 'Copywriting, essays, articles, blogs'
purpose: []
