name: HemlockforSocrates
favicon: null
layout_spectrum: 0.83301
typography_spectrum: 0.4384060010779649
title: Freelance Writer for hire
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbf8f3'
    - '#e5c0a4'
    - '#c18458'
    - '#010104'
    - '#434434'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.7869873542804271
  rhythmicContrast: 0.48784929513931274
purpose: []
